# Generated by Django 4.1 on 2022-08-05 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_rename_tags_tag"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["status", "-datetime"]},
        ),
    ]
